# Generated by Django 5.1.1 on 2024-09-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='c9a9bc68fbfa411881343e614a12d4dd', max_length=255, unique=True),
        ),
    ]
