# Generated by Django 5.1.1 on 2024-09-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='b8e876f8db4642e59ec21722a452647d', max_length=255, unique=True),
        ),
    ]
