# Generated by Django 5.1.1 on 2024-09-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='e653a13b96e540138e2d37781433ab63', max_length=255, unique=True),
        ),
    ]
