# Generated by Django 5.1.1 on 2024-09-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='4939c9ff7cb340b7ab957f74ee50a590', max_length=255, unique=True),
        ),
    ]
