# Generated by Django 5.1.1 on 2024-09-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='ac7d67f60e5d4d019075536e17b3ffcd', max_length=255, unique=True),
        ),
    ]
