# Generated by Django 5.1.1 on 2024-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='ea8ad5115f28459fba0a5d9dd3dff44b', max_length=255, unique=True),
        ),
    ]
