# Generated by Django 5.1.1 on 2024-09-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='0f3e00cc2db14d6ba6c5e4944279c974', max_length=255, unique=True),
        ),
    ]
