# Generated by Django 5.1.1 on 2024-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='826aa1589a0942ddad9a7c8f66772636', max_length=255, unique=True),
        ),
    ]
