# Generated by Django 5.1.1 on 2024-11-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content_md',
            field=models.TextField(blank=True, null=True),
        ),
    ]
