# Generated by Django 5.1.1 on 2024-09-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_suggestion_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='REJECTED', max_length=8),
        ),
    ]
