# Generated by Django 5.1.1 on 2024-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_alter_suggestion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPromptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('internal_linking', models.TextField()),
            ],
        ),
    ]
