# Generated by Django 5.1.1 on 2024-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_sitemapindex_publish_token_alter_sitemapindex_user'),
        ('seo', '0010_article_academy_id'),
    ]

    operations = [
    ]
